Change tab from 2 to 4 spaces

diff --git a/.local/bin/h b/.local/bin/h
--- a/.local/bin/h
+++ b/.local/bin/h
@@ -3,33 +3,33 @@
 # Show command's help page with syntax highlighting
 
 if command -v bat >/dev/null 2>&1; then
-  pager_cmd=(bat -plhelp)
+    pager_cmd=(bat -plhelp)
 else
-  pager_cmd=(less)
+    pager_cmd=(less)
 fi
 
 # Number of arguments is one
 if (( "${#@}" == 1 )); then
-  if "$1" --help >/dev/null 2>&1; then
-    "$1" --help | "${pager_cmd[@]}"
-  elif help "$1" >/dev/null 2>&1; then
-    help "$1" | "${pager_cmd[@]}"
-  elif "$1" -h >/dev/null 2>&1; then
-    "$1" -h | "${pager_cmd[@]}"
-  else
-    echo -e "\e[1;31mError\e[0m: no help found for command '$*'"
-    exit 1
-  fi
+    if "$1" --help >/dev/null 2>&1; then
+        "$1" --help | "${pager_cmd[@]}"
+    elif help "$1" >/dev/null 2>&1; then
+        help "$1" | "${pager_cmd[@]}"
+    elif "$1" -h >/dev/null 2>&1; then
+        "$1" -h | "${pager_cmd[@]}"
+    else
+        echo -e "\e[1;31mError\e[0m: no help found for command '$*'"
+        exit 1
+    fi
 # Number of arguments is greater than one
 elif (( "${#@}" > 1 )); then
-  if "$1" "help" "${@:2}" >/dev/null 2>&1; then
-    "$1" "help" "${@:2}" | "${pager_cmd[@]}"
-  elif "$@" --help >/dev/null 2>&1; then
-    "$@" --help | "${pager_cmd[@]}"
-  else
-    echo -e "\e[1;31mError\e[0m: no help found, try 'man $*'"
-    exit 1
-  fi
+    if "$1" "help" "${@:2}" >/dev/null 2>&1; then
+        "$1" "help" "${@:2}" | "${pager_cmd[@]}"
+    elif "$@" --help >/dev/null 2>&1; then
+        "$@" --help | "${pager_cmd[@]}"
+    else
+        echo -e "\e[1;31mError\e[0m: no help found, try 'man $*'"
+        exit 1
+    fi
 else
-  echo "Usage: h [COMMAND] [SUBCOMMAND]" | "${pager_cmd[@]}"
+    echo "Usage: h [COMMAND] [SUBCOMMAND]" | "${pager_cmd[@]}"
 fi
diff --git a/.local/bin/virt-viewer b/.local/bin/virt-viewer
--- a/.local/bin/virt-viewer
+++ b/.local/bin/virt-viewer
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 
 if command -v virt-viewer >/dev/null 2>&1; then
-  virt_viewer=()
-  virt_viewer+=('/usr/bin/virt-viewer')
-  virt_viewer+=('--connect=qemu:///system')
-  virt_viewer+=('--hotkeys=release-cursor=alt+enter')
-  virt_viewer+=('--wait')
-  GDK_BACKEND=x11 command "${virt_viewer[@]}" "$@" >> ~/.virt_viewer.log 2>&1 &
+    virt_viewer=()
+    virt_viewer+=('/usr/bin/virt-viewer')
+    virt_viewer+=('--connect=qemu:///system')
+    virt_viewer+=('--hotkeys=release-cursor=alt+enter')
+    virt_viewer+=('--wait')
+    GDK_BACKEND=x11 command "${virt_viewer[@]}" "$@" >> ~/.virt_viewer.log 2>&1 &
 else
-  echo -e "\e[1;31mError\e[0m: virt-viewer executable not found."
-  exit 1
+    echo -e "\e[1;31mError\e[0m: virt-viewer executable not found."
+    exit 1
 fi
