Use less if bat not found

diff --git a/.local/bin/h b/.local/bin/h
--- a/.local/bin/h
+++ b/.local/bin/h
@@ -3,32 +3,33 @@
 # Show command's help page with syntax highlighting
 
 if command -v bat >/dev/null 2>&1; then
-  # Number of arguments is one
-  if (( "${#@}" == 1 )); then
-    if "$1" --help >/dev/null 2>&1; then
-      "$1" --help | bat -plhelp
-    elif help "$1" >/dev/null 2>&1; then
-      help "$1" | bat -plhelp
-    elif "$1" -h >/dev/null 2>&1; then
-      "$1" -h | bat -plhelp
-    else
-      echo -e "\e[1;31mError\e[0m: no help found for command '$*'"
-      exit 1
-    fi
-  # Number of arguments is greater than one
-  elif (( "${#@}" > 1 )); then
-    if "$1" "help" "${@:2}" >/dev/null 2>&1; then
-      "$1" "help" "${@:2}" | bat -plhelp
-    elif "$@" --help >/dev/null 2>&1; then
-      "$@" --help | bat -plhelp
-    else
-      echo -e "\e[1;31mError\e[0m: no help found, try 'man $*'"
-      exit 1
-    fi
+  pager_cmd=(bat -plhelp)
+else
+  pager_cmd=(less)
+fi
+
+# Number of arguments is one
+if (( "${#@}" == 1 )); then
+  if "$1" --help >/dev/null 2>&1; then
+    "$1" --help | "${pager_cmd[@]}"
+  elif help "$1" >/dev/null 2>&1; then
+    help "$1" | "${pager_cmd[@]}"
+  elif "$1" -h >/dev/null 2>&1; then
+    "$1" -h | "${pager_cmd[@]}"
   else
-    echo "Usage: h [COMMAND] [SUBCOMMAND]" | bat -plhelp
+    echo -e "\e[1;31mError\e[0m: no help found for command '$*'"
+    exit 1
+  fi
+# Number of arguments is greater than one
+elif (( "${#@}" > 1 )); then
+  if "$1" "help" "${@:2}" >/dev/null 2>&1; then
+    "$1" "help" "${@:2}" | "${pager_cmd[@]}"
+  elif "$@" --help >/dev/null 2>&1; then
+    "$@" --help | "${pager_cmd[@]}"
+  else
+    echo -e "\e[1;31mError\e[0m: no help found, try 'man $*'"
+    exit 1
   fi
 else
-  echo -e "\e[1;31mError\e[0m: \e[1mbat\e[0m: not found"
-  exit 1
+  echo "Usage: h [COMMAND] [SUBCOMMAND]" | "${pager_cmd[@]}"
 fi
