Fix uv/fzf check

diff --git a/.local/bin/pt b/.local/bin/pt
--- a/.local/bin/pt
+++ b/.local/bin/pt
@@ -17,10 +17,12 @@ if [[ "$*" =~ (-h|--help) ]]; then
 fi
 
 # Check for uv/fzf presence
-command -v uv >/dev/null 2>&1 || \
-  echo -e '\e[1;31mError\e[0m: \e[1muv\e[0m required but not found.'
-command -v fzf >/dev/null 2>&1 || \
-  echo -e '\e[1;31mError\e[0m: \e[1mfzf\e[0m required but not found.'
+for x in 'uv' 'fzf'; do
+  if ! command -v "$x" >/dev/null 2>&1; then
+    echo -e "\e[1;31mError\e[0m: \e[1m${x}\e[0m required but not found."
+    exit 1
+  fi
+done
 
 # Choose repl based on command name
 case "$(basename "$0")" in
