Remove VIRTUAL_ENV check

diff --git a/.local/bin/pt b/.local/bin/pt
--- a/.local/bin/pt
+++ b/.local/bin/pt
@@ -4,7 +4,7 @@
 #
 # Choose python repl and modules
 
-if [[ "$*" =~ (-h|--help) ]]; then
+if [[ "$*" =~ (-h|--help)$ ]]; then
     echo "Usage:"
     echo -e "\tipy: ipython"
     echo -e "\tpti: ptipython"
@@ -17,82 +17,79 @@ if [[ "$*" =~ (-h|--help) ]]; then
 fi
 
 # Check for uv/fzf presence
-for x in 'uv' 'fzf'; do
-    if ! command -v "$x" >/dev/null 2>&1; then
-        echo -e "\e[1;31mError\e[0m: \e[1m${x}\e[0m required but not found."
-        exit 1
-    fi
-done
+if ! command -v uv >/dev/null 2>&1; then
+    echo -e "\e[1;31mError\e[0m: \e[1muv\e[0m required but not found."
+    exit 1
+fi
+if ! command -v fzf >/dev/null 2>&1; then
+    echo -e "\e[1;31mError\e[0m: \e[1mfzf\e[0m required but not found."
+    exit 1
+fi
 
 # Choose repl based on command name
 case "$(basename "$0")" in
-    ipy) repl='ipython --profile=ipy' ;;
-    pti) repl='--from ptpython ptipython'; add_ipython='ipython' ;;
-    *)  repl='ptpython' ;;
+    ipy) repl='ipython --profile=ipy'                               ;;
+    pti) repl='--from ptpython ptipython'; add_ipython='ipython'    ;;
+      *) repl='ptpython'                                            ;;
 esac
 
 # Additional modules
 # add_modules='rich'
 
-# In a virtual environment no need to choose modules
-if [[ -v VIRTUAL_ENV ]]; then
-    add_modules=
-else
-    # Get virtual environment path
-    venv_path="$(realpath .)"
-    until [[ -d "$venv_path/.venv" ]]; do
-        if [[ "$venv_path" == '/' ]]; then
-            if [[ -d ~/Code/.venv ]]; then
-                venv_path="$(realpath ~/Code)"
-            else
-                venv_path=''
-            fi
-            break
-        fi
-        venv_path="$(dirname "$venv_path")"
-    done
-    if [[ -n "$venv_path" ]]; then
-        # List modules in virtual environment
-        uv_pip_list="$(uv pip list -q --directory "$venv_path")"
-    else
-        # Do not list systemwide modules
-        uv_pip_list=''
-    fi
-
-    # Create an array of chosen modules
-    mapfile -t modules < <(
-        echo   -e "$uv_pip_list" |
-            sed -n '3,$p'        |
-            awk    '{print $1}'  |
-            cat ~/.pti_history - 2>/dev/null |
-            sed    '/^$/d'       |
-            fzf --multi --height ~25% --print-query --layout reverse --border
-        )
-
-    if [[ -n "${modules[*]}" ]]; then
-        # If first line (query) starts with '+' remove plus, else remove line
-        if [[ -n "${modules[0]}" && "${modules[0]}" =~ ^\+ ]]; then
-            modules[0]="${modules[0]#+}"
+# Get virtual environment path
+venv_path="$(realpath .)"
+until [[ -d "$venv_path/.venv" ]]; do
+    if [[ "$venv_path" == '/' ]]; then
+        if [[ -d ~/Code/.venv ]]; then
+            venv_path="$(realpath ~/Code)"
         else
-            unset 'modules[0]'
+            venv_path=''
         fi
-        for line in "${modules[@]}"; do
-            # Check for invalid characters
-            if ! [[ "$line" =~ ^[a-zA-Z0-9_.,-]*$ ]]; then
-             echo -e "\x1b[31mError\x1b[0m: Invalid module name: '$line'"
-             exit 1
-            fi
-        done
-        # Add comma separated modules to history
-        [[ -f ~/.pti_history ]] && mapfile -t old_history < ~/.pti_history
-        new_history=("$(IFS=, ; echo "${modules[*]}")")
-        for (( i=0; i < ${#old_history[@]}; i++ )); do
-            [[ -n "${old_history[$i]}" ]] && \
-            [[ "${new_history[0]}" != "${old_history[$i]}" ]] && \
-                    new_history+=("${old_history[$i]}")
-        done
-        printf "%s\n" "${new_history[@]}" > ~/.pti_history
+        break
     fi
+    venv_path="$(dirname "$venv_path")"
+done
+if [[ -n "$venv_path" ]]; then
+    # List modules in virtual environment
+    uv_pip_list="$(uv pip list -q --directory "$venv_path")"
+else
+    # Do not list systemwide modules
+    uv_pip_list=''
+fi
+
+# Create an array of chosen modules
+mapfile -t modules < <(
+    echo   -e "$uv_pip_list" |
+        sed -n '3,$p'        |
+        awk    '{print $1}'  |
+        cat ~/.pti_history - 2>/dev/null |
+        sed    '/^$/d'       |
+        fzf --multi --height ~25% --print-query --layout reverse --border
+    )
+
+if [[ -n "${modules[*]}" ]]; then
+    # If first line (query) starts with '+' remove plus, else remove line
+    if [[ -n "${modules[0]}" && "${modules[0]}" =~ ^\+ ]]; then
+        modules[0]="${modules[0]#+}"
+    else
+        unset 'modules[0]'
+    fi
+    for line in "${modules[@]}"; do
+        # Check for invalid characters
+        if ! [[ "$line" =~ ^[a-zA-Z0-9_.,-]*$ ]]; then
+         echo -e "\x1b[31mError\x1b[0m: Invalid module name: '$line'"
+         exit 1
+        fi
+    done
+    # Add comma separated modules to history
+    [[ -f ~/.pti_history ]] && mapfile -t old_history < ~/.pti_history
+    new_history=("$(IFS=, ; echo "${modules[*]}")")
+    for (( i=0; i < ${#old_history[@]}; i++ )); do
+        [[ -n "${old_history[$i]}" ]] && \
+        [[ "${new_history[0]}" != "${old_history[$i]}" ]] && \
+                new_history+=("${old_history[$i]}")
+    done
+    printf "%s\n" "${new_history[@]}" > ~/.pti_history
 fi
 
 # Add modules
